name: ci

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code repository
        uses: actions/checkout@v4
        
      - name: run pre-commit
        uses: pre-commit/action@v3.0.0
