name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:name: deploy

steps:
  # checkout github repos: this repo, plus, all Github Actions repos in this workflow
  - name: Checkout
    uses: actions/checkout@v3
    
  # install doctl CLI
  - name: install doctl
    uses: digitalocean/action-doctl@v2
    with:
      token: ${{ secrets.DO_ACCESS_TOKEN }}

  - name: setup conda environment with mambaforge
    uses: conda-incubator/setup-miniconda@v2
    with:
      use-mamba: true
      activate-environment: landscape-diarrhea-civ
      environment-file: environment.yml
      miniforge-variant: Mambaforge
      miniforge-version: 4.14.0-0
          
  # init env
  - name: configure kubectl
    run: |-
      sudo snap install kubectl --chanel=1.23/stable --classic
      doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}
      echo "kubectl version and diagnostic info:"
      echo "------------------------------------"
      kubectl version --short --v=9


  - name: install tutor

  - name: load tutor settings
    shell: bash
    run: |-
      echo "TUTOR_RUN_CADDY=false" >> $GITHUB_ENV
      echo "TUTOR_RUN_NGINX=false" >> $GITHUB_ENV

  - name: load additional tutor environment specific settings
    shell: bash
    run: |-
      echo "TUTOR_ID=tutor-${{ env.CLUSTER_NAME }}" >> $GITHUB_ENV
      echo "TUTOR_K8S_NAMESPACE=${{ env.CLUSTER_NAME }}" >> $GITHUB_ENV      
